//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirReservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirReservationDBMvcEntities : DbContext
    {
        public AirReservationDBMvcEntities()
            : base("name=AirReservationDBMvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingFlight> BookingFlights { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FlightInfo> FlightInfoes { get; set; }
        public virtual DbSet<PassengerInfo> PassengerInfoes { get; set; }
    }
    public class SelectedInfoModel
    {
        public IEnumerable<PassengerInfo> passengers { get; set; }
        public IEnumerable<Country> countries { get; set; }
        public IEnumerable<BookingFlight> bookingFlights { get; set; }
    }
}
