//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirReservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingFlight
    {
        public int BookID { get; set; }
        [Required]
        [DisplayName("From Place")]
        public string FromPlace { get; set; }
        [Required]
        public string Destination { get; set; }
        [Required]
        [DisplayName("Flight Date")]
        [DataType(DataType.Date)]
        public string FlightDate { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> CountryID { get; set; }
        [DisplayName("Flight ID")]
        public Nullable<int> FlightID { get; set; }

        public virtual Country Country { get; set; }
        public virtual FlightInfo FlightInfo { get; set; }
        public virtual PassengerInfo PassengerInfo { get; set; }
    }
}
